/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_in;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 皮皮
 */
public class forgetpassword extends javax.swing.JFrame {

   private  Connection con = null;
    private PreparedStatement pst;
    private ResultSet rs;
    private String sql = null;
    private double secLeft = 10.0;
    Thread t;

    /**
     * Creates new form forgetpassword
     */
    public forgetpassword() {
        initComponents();
        jPanel2.setVisible(false);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTYourYN = new javax.swing.JTextField();
        jTYourPN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        J1 = new javax.swing.JTextField();
        J3 = new javax.swing.JTextField();
        J5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        J4 = new javax.swing.JButton();
        J6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retrieve Password");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setEnabled(false);
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("华文中宋", 1, 48)); // NOI18N
        jLabel2.setText("Retrieve Password");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 500, 48));

        jLabel4.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel4.setText("Your Phone Number");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 30));

        jTYourYN.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jPanel3.add(jTYourYN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 202, 30));

        jTYourPN.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jPanel3.add(jTYourPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 202, 30));

        jLabel3.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel3.setText("Your User Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 30));

        Submit.setFont(new java.awt.Font("黑体", 2, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });
        jPanel3.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        Cancel.setFont(new java.awt.Font("黑体", 2, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelMouseReleased(evt);
            }
        });
        jPanel3.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 660, 320));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        J1.setFont(new java.awt.Font("黑体", 1, 36)); // NOI18N
        J1.setEnabled(false);
        jPanel2.add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 523, 43));

        J3.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(J3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 160, 20));

        J5.setFont(new java.awt.Font("黑体", 2, 18)); // NOI18N
        J5.setText("Login");
        J5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                J5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                J5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                J5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                J5MouseReleased(evt);
            }
        });
        jPanel2.add(J5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(570, 170));

        J4.setFont(new java.awt.Font("黑体", 2, 18)); // NOI18N
        J4.setText("New User");
        J4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                J4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                J4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                J4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                J4MouseReleased(evt);
            }
        });

        J6.setFont(new java.awt.Font("黑体", 2, 18)); // NOI18N
        J6.setText("Try Again");
        J6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                J6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                J6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                J6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                J6MouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N
        jLabel5.setText("You are wrong with your Username or phonenumber");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(J6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(J4)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(J6)
                    .addComponent(J4))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Cache_-2e8a9f2d6617e3c1..jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        try {
            con = (Connection) new Connective().getConnection();
            sql = "select *  from User_Details where User_name=? and User_phone=?";
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, jTYourYN.getText());
            pst.setString(2, jTYourPN.getText());
            rs = pst.executeQuery();
            if (jTYourYN.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Empty Username", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jTYourPN.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Empty Phone Number", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (rs.next()) {
                String YSN = "Your Password is " + rs.getString("User_password");
                jPanel2.setVisible(true);
                J1.setText(YSN);
                
                t = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        jPanel2.setVisible(true);
                        jPanel4.setVisible(false);
                        while (secLeft > 0) {
                            try {
                                t.sleep(10);
                            } catch (InterruptedException ex) {
                                System.out.println(ex);
                            }
                            String abcd = String.format("%5.2f", secLeft) + "s automatic return";
                            J3.setText(abcd);
                            secLeft -= 0.01;
                        }
                        dispose();
                        try {
                            Open.LI(jTYourYN.getText());
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    }
                });

                t.start();
            } else {
                jPanel2.setVisible(true);
                jPanel4.setVisible(true);
                J1.setVisible(false);
                J3.setVisible(false);
                J5.setVisible(false);
            }
            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SubmitMouseClicked

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
        Submit.setForeground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        Submit.setForeground(null);
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseExited

    private void SubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMousePressed
        Submit.setForeground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitMousePressed

    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseReleased
        Submit.setForeground(null);
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseReleased

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        int ans = JOptionPane.showConfirmDialog(this, "Are you sure？ ", "confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            Open.LI();
            dispose();
        }
    }//GEN-LAST:event_CancelMouseClicked

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setForeground(Color.blue);
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setForeground(null);
// TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseExited

    private void CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMousePressed
        Cancel.setForeground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_CancelMousePressed

    private void CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseReleased
        Cancel.setForeground(null);
// TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseReleased

    private void J6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J6MouseReleased
        J6.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_J6MouseReleased

    private void J6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J6MousePressed
        J6.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_J6MousePressed

    private void J6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J6MouseExited
        J6.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_J6MouseExited

    private void J6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J6MouseEntered
        J6.setForeground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_J6MouseEntered

    private void J6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J6MouseClicked
        Open.FP();
        dispose();
    }//GEN-LAST:event_J6MouseClicked

    private void J4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J4MouseReleased
        J4.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_J4MouseReleased

    private void J4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J4MousePressed
        J4.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_J4MousePressed

    private void J4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J4MouseExited
        J4.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_J4MouseExited

    private void J4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J4MouseEntered
        J4.setForeground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_J4MouseEntered

    private void J4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J4MouseClicked
        Open.R();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_J4MouseClicked

    private void J5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J5MouseReleased
        J5.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_J5MouseReleased

    private void J5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J5MousePressed
        J5.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_J5MousePressed

    private void J5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J5MouseExited
        J5.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_J5MouseExited

    private void J5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J5MouseEntered
        J5.setForeground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_J5MouseEntered

    private void J5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J5MouseClicked
        secLeft = 0;
    }//GEN-LAST:event_J5MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J3;
    private javax.swing.JButton J4;
    private javax.swing.JButton J5;
    private javax.swing.JButton J6;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTYourPN;
    private javax.swing.JTextField jTYourYN;
    // End of variables declaration//GEN-END:variables
}
