/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_in;

import frame.MainFrame;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import static model.Level.setlive;

/**
 *
 * @author 皮皮
 */
public class Keep_file extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst;
    ResultSet rs;
    String user = welcome.getUser();
    Object[][] a = new Object[50][5];
    int count = 0;

    /**
     * Creates new form Keep_file
     */
    public Keep_file() {
        initComponents();
        showkeep();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JT1 = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JT.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        JT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Time", "Level"
            }
        ));
        jScrollPane1.setViewportView(JT);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 780, 360));

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        jLabel2.setText("Playing    Record");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 321, -1));

        Cancel.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Cancel.setText("Back");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelcancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelcancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelcancelMouseReleased(evt);
            }
        });
        Cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CancelcancelKeyReleased(evt);
            }
        });
        jPanel2.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 127, 36));

        jLabel3.setFont(new java.awt.Font("黑体", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Please enter the number of your want ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, 20));

        JT1.setFont(new java.awt.Font("黑体", 1, 15)); // NOI18N
        jPanel2.add(JT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 40, -1));

        Submit.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitsubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitsubmitMouseReleased(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel2.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 117, 36));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Cache_-2e8a9f2d6617e3c1..jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelcancelMouseClicked
        Open.W(user);
        dispose();

    }//GEN-LAST:event_CancelcancelMouseClicked

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setForeground(Color.blue);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setForeground(null);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseExited

    private void CancelcancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelcancelMousePressed
        Cancel.setForeground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_CancelcancelMousePressed

    private void CancelcancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelcancelMouseReleased
        Cancel.setForeground(null);// TODO add your handling code here:
    }//GEN-LAST:event_CancelcancelMouseReleased

    private void CancelcancelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CancelcancelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelcancelKeyReleased

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        
        if (JT1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "You have not enter.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Integer.parseInt(JT1.getText()) < 1 || Integer.parseInt(JT1.getText()) > count) {
            JOptionPane.showMessageDialog(this, "Your input is incorrect.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            for (int x = 0; x < count; x++) {
                if (Integer.parseInt(JT1.getText()) == Integer.parseInt(a[x][3].toString())) {
                    setlive(Integer.parseInt(a[x][2].toString()));
                    try {
                        con = Connective.getConnection();
                        String sql = "delete from " + user + " where UID = ?";
                        pst = con.prepareStatement(sql);
                        pst.setInt(1, Integer.parseInt((String) a[x][4]));
                        pst.executeUpdate();
                        pst.close();
                        con.close();
                        dispose();
                    } catch (ClassNotFoundException ex) {
                        System.out.println(ex);
                    } catch (NumberFormatException ex) {
                        System.out.println(ex);
                    } catch (SQLException ex) {
                        System.out.println(ex);
                    }
                    MainFrame frame = new MainFrame();
                    frame.setVisible(true);
                }                
            }
        }

    }//GEN-LAST:event_SubmitMouseClicked

    private void SubmitsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitsubmitMouseEntered
        Submit.setForeground(Color.blue);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitsubmitMouseEntered

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        Submit.setForeground(null);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseExited

    private void SubmitsubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitsubmitMousePressed
        Submit.setForeground(Color.red);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitsubmitMousePressed

    private void SubmitsubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitsubmitMouseReleased
        Submit.setForeground(null);// TODO add your handling code here:
    }//GEN-LAST:event_SubmitsubmitMouseReleased

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed
    
    @SuppressWarnings("empty-statement")
    private void showkeep() {
        try {
            con = new Connective().getConnection();
            String sql = "select Date_format(Utime,'%Y-%m-%d %T'),Ulevel,UID from  " + user;
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel tm = (DefaultTableModel) JT.getModel();
            tm.addColumn("Number");
            int i = 1;
            for (int j = 0; rs.next(); j++, i++) {
                
                for (int s = 1; s < 3; s++) {
                    a[j][0] = user;
                    a[j][s] = rs.getString(s);
                    a[j][3] = j + 1;
                }
                tm.addRow(a[j]);
                a[j][4] = rs.getString(3);
                count = j + 1;
            }
            tm.fireTableDataChanged();
            rs.close();
            pst.close();
            con.close();
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTable JT;
    private javax.swing.JTextField JT1;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
