/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_in;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 皮皮
 */
public class Login_in extends javax.swing.JFrame {

    /**
     * Creates new form Login_in
     */
    Connection con = null;
    PreparedStatement pst;
    ResultSet rs;
    public String User = null;

    public Login_in() {
        initComponents();
        setResizable(false);
    }

    public Login_in(String abc) {
        initComponents();
        jTUsername.setText(abc);
        setResizable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLUN = new javax.swing.JLabel();
        jTUsername = new javax.swing.JTextField();
        jLNU = new javax.swing.JLabel();
        jLUN1 = new javax.swing.JLabel();
        jPPassword = new javax.swing.JPasswordField();
        jLFP = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLFP1 = new javax.swing.JLabel();
        dsvknlskv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUN.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLUN.setText("Username");
        jPanel1.add(jLUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 405, 188, 58));

        jTUsername.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jPanel1.add(jTUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 406, 218, -1));

        jLNU.setFont(new java.awt.Font("华文隶书", 2, 60)); // NOI18N
        jLNU.setForeground(new java.awt.Color(255, 0, 0));
        jLNU.setText("new user?");
        jLNU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLNUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLNUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLNUMouseExited(evt);
            }
        });
        jPanel1.add(jLNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 460, 82));

        jLUN1.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLUN1.setText("Password");
        jPanel1.add(jLUN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 488, 188, 58));

        jPPassword.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jPPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 489, 218, -1));

        jLFP.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLFP.setForeground(new java.awt.Color(51, 51, 255));
        jLFP.setText("Forget Password?");
        jLFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLFPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLFPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLFPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLFPMouseReleased(evt);
            }
        });
        jPanel1.add(jLFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, -1, -1));

        Submit.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                submitMouseReleased(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 117, 36));

        Cancel.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelMouseReleased(evt);
            }
        });
        Cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cancelKeyReleased(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 127, 36));

        jLFP1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLFP1.setForeground(new java.awt.Color(51, 0, 255));
        jLFP1.setText("Forget Username?");
        jLFP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLFP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLFP1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLFP1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLFP1MouseReleased(evt);
            }
        });
        jPanel1.add(jLFP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        dsvknlskv.setFont(new java.awt.Font("华文行楷", 1, 60)); // NOI18N
        dsvknlskv.setText("National     Missile    Defense");
        dsvknlskv.setToolTipText("National     Missile    Defense");
        jPanel1.add(dsvknlskv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 750, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Cache_26de8fed954b334d..jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void cancelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelKeyReleased

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked

        
        try {
            con = Connective.getConnection();
            String sql = "select * from User_Details where User_name=? and User_password=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, jTUsername.getText());
            pst.setString(2, jPPassword.getText());
            rs = pst.executeQuery();
            if (jTUsername.getText().length() == 0) {
                JOptionPane.showMessageDialog(this, "Empty Username", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jPPassword.getPassword().length == 0) {
                JOptionPane.showMessageDialog(this, "Empty Password", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (rs.next()) {
                User = jTUsername.getText();
                Open.W(User);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Your Username or password is wrong", "Warning", JOptionPane.WARNING_MESSAGE);
            }
            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_SubmitMouseClicked
   
        private void jLFP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFP1MouseClicked
            Open.FU();
            dispose();
    }//GEN-LAST:event_jLFP1MouseClicked

    private void jLFPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFPMouseClicked
        Open.FP();         
        dispose();
    }//GEN-LAST:event_jLFPMouseClicked

    private void jLNUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNUMouseClicked
        Open.R();
        dispose();
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_jLNUMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        int ans = JOptionPane.showConfirmDialog(this, "Are you so cruel?", "confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            this.dispose();
            Open.LI();
        }
    }//GEN-LAST:event_cancelMouseClicked

    private void jLFPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFPMouseEntered
        jLFP.setForeground(Color.red);
        jLFP.setFont(new Font("Trebuchet MS", 3, 25));
    }//GEN-LAST:event_jLFPMouseEntered

    private void jLFP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFP1MouseEntered
        jLFP1.setForeground(Color.red);
        jLFP1.setFont(new Font("Trebuchet MS", 3, 25));// TODO add your handling code here:
    }//GEN-LAST:event_jLFP1MouseEntered

    private void jLFPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFPMouseExited
        jLFP.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLFP.setForeground(new java.awt.Color(51, 51, 255));       // TODO add your handling code here:
    }//GEN-LAST:event_jLFPMouseExited

    private void jLFPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFPMousePressed
        jLFP.setFont(new java.awt.Font("Trebuchet MS", 3, 27)); // NOI18N

    }//GEN-LAST:event_jLFPMousePressed

    private void jLFPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFPMouseReleased
        jLFP.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLFP.setForeground(new java.awt.Color(51, 51, 255));
    }//GEN-LAST:event_jLFPMouseReleased

    private void jLFP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFP1MouseExited
        jLFP1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLFP1.setForeground(new java.awt.Color(51, 51, 255));// TODO add your handling code here:
    }//GEN-LAST:event_jLFP1MouseExited

    private void jLFP1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFP1MousePressed
        jLFP.setFont(new java.awt.Font("Trebuchet MS", 3, 27));// TODO add your handling code here:
    }//GEN-LAST:event_jLFP1MousePressed

    private void jLFP1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFP1MouseReleased
        jLFP1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLFP1.setForeground(new java.awt.Color(51, 51, 255));// TODO add your handling code here:
    }//GEN-LAST:event_jLFP1MouseReleased

    private void cancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMousePressed
        Cancel.setForeground(Color.red);// TODO add your handling code here:
    }//GEN-LAST:event_cancelMousePressed

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        Submit.setForeground(Color.blue);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_submitMouseEntered

    private void submitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMousePressed
        Submit.setForeground(Color.red);// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_submitMousePressed

    private void submitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseReleased
        Submit.setForeground(null);// TODO add your handling code here:
    }//GEN-LAST:event_submitMouseReleased

    private void cancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseReleased
        Cancel.setForeground(null);// TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseReleased

    private void jLNUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNUMouseEntered
        jLNU.setFont(new java.awt.Font("华文隶书", 3, 65)); // NOI18N
        jLNU.setText("Register Now");// TODO add your handling code here:
    }//GEN-LAST:event_jLNUMouseEntered

    private void jLNUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNUMouseExited
        jLNU.setFont(new java.awt.Font("华文隶书", 2, 60)); // NOI18N
        jLNU.setForeground(new java.awt.Color(255, 0, 0));
        jLNU.setText("new user?");// TODO add your handling code here:
    }//GEN-LAST:event_jLNUMouseExited

    private void jPPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPPasswordActionPerformed

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        Submit.setForeground(null);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setForeground(Color.blue);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setForeground(null);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseExited
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel dsvknlskv;
    private javax.swing.JLabel jLFP;
    private javax.swing.JLabel jLFP1;
    private javax.swing.JLabel jLNU;
    private javax.swing.JLabel jLUN;
    private javax.swing.JLabel jLUN1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTUsername;
    // End of variables declaration//GEN-END:variables
}
