/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_in;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author 皮皮
 */
public class register extends javax.swing.JFrame {

    Pattern use = Pattern.compile("^[A-Za-z_]+[A-Za-z]\\d{0,7}+$");
    Pattern passw = Pattern.compile("^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,16}$");
    Pattern email = Pattern.compile("^(\\w)+(\\.\\w+)*@(\\w)+((\\.\\w{2,3}){1,3})$");
    Pattern phone = Pattern.compile("^((13[0-9])|(15[^4,\\D])|(18[0,5-9]))\\d{8}$");
    Connection con = null;
    PreparedStatement pst;
    ResultSet rs, rsp, rsu;

    public register() {
        initComponents();
        JL11.setVisible(false);
        JL12.setVisible(false);
        JL21.setVisible(false);
        JL22.setVisible(false);
        JL31.setVisible(false);
        JL32.setVisible(false);
        JL42.setVisible(false);
        JL52.setVisible(false);
        JT2.setEnabled(false);
        JP1.setEnabled(false);
        JP2.setEnabled(false);
        JT3.setEnabled(false);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JT2 = new javax.swing.JTextField();
        JT1 = new javax.swing.JTextField();
        JT3 = new javax.swing.JTextField();
        JP1 = new javax.swing.JPasswordField();
        JP2 = new javax.swing.JPasswordField();
        Cancel = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        JL11 = new javax.swing.JLabel();
        JL21 = new javax.swing.JLabel();
        JL31 = new javax.swing.JLabel();
        JL12 = new javax.swing.JLabel();
        JL22 = new javax.swing.JLabel();
        JL32 = new javax.swing.JLabel();
        JL42 = new javax.swing.JLabel();
        JL52 = new javax.swing.JLabel();
        Cancel1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(960, 960));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(964, 584));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 60)); // NOI18N
        jLabel2.setText("New User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 320, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel3.setText("Password ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 222, 250, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 250, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel5.setText("Password Confirm");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 295, 370, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 446, 250, -1));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel7.setText("Phone Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 350, -1));

        JT2.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        JT2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT2MouseClicked(evt);
            }
        });
        JT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT2ActionPerformed(evt);
            }
        });
        jPanel1.add(JT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 380, 210, 40));

        JT1.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        JT1.setToolTipText("");
        JT1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JT1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JT1MouseExited(evt);
            }
        });
        JT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT1ActionPerformed(evt);
            }
        });
        jPanel1.add(JT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 187, -1));

        JT3.setFont(new java.awt.Font("黑体", 0, 24)); // NOI18N
        JT3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT3MouseClicked(evt);
            }
        });
        jPanel1.add(JT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 450, 210, 40));

        JP1.setFont(new java.awt.Font("宋体", 0, 11)); // NOI18N
        JP1.setMargin(new java.awt.Insets(2, 0, 2, 6));
        JP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP1MouseExited(evt);
            }
        });
        jPanel1.add(JP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 187, 40));

        JP2.setFont(new java.awt.Font("宋体", 0, 11)); // NOI18N
        JP2.setMargin(new java.awt.Insets(2, 0, 2, 6));
        JP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JP2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP2MouseExited(evt);
            }
        });
        jPanel1.add(JP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 187, 40));

        Cancel.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelMouseReleased(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, -1, -1));

        Submit.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SubmitMouseReleased(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, -1, -1));

        JL11.setForeground(new java.awt.Color(51, 51, 255));
        JL11.setText("No more than 8 letters");
        jPanel1.add(JL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 145, 14));

        JL21.setForeground(new java.awt.Color(51, 51, 255));
        JL21.setText("Between 8 and 16 including numbers and letters");
        jPanel1.add(JL21, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 280, 14));

        JL31.setForeground(new java.awt.Color(51, 51, 255));
        JL31.setText("Should be same with password");
        jPanel1.add(JL31, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, 14));

        JL12.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        JL12.setForeground(new java.awt.Color(255, 51, 51));
        JL12.setText("Too long !");
        jPanel1.add(JL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        JL22.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        JL22.setForeground(new java.awt.Color(255, 51, 51));
        JL22.setText("Too short!");
        jPanel1.add(JL22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        JL32.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        JL32.setForeground(new java.awt.Color(255, 51, 51));
        JL32.setText("Not same!");
        jPanel1.add(JL32, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, -1, -1));

        JL42.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        JL42.setForeground(new java.awt.Color(255, 51, 51));
        JL42.setText("Has been used");
        jPanel1.add(JL42, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        JL52.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        JL52.setForeground(new java.awt.Color(255, 51, 51));
        JL52.setText("Has been used");
        jPanel1.add(JL52, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, -1, -1));

        Cancel1.setFont(new java.awt.Font("黑体", 0, 18)); // NOI18N
        Cancel1.setText("Login");
        Cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cancel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cancel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cancel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Cancel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Cancel1MouseReleased(evt);
            }
        });
        jPanel1.add(Cancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 988, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Cache_-2e8a9f2d6617e3c1..jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseReleased
        Cancel.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseReleased

    private void CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMousePressed
        Cancel.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMousePressed

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        Cancel.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setForeground(Color.blue);
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
        int ans = JOptionPane.showConfirmDialog(this, "Are you so cruel?", "confirm", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_CancelMouseClicked

    private void SubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseReleased
        Submit.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseReleased

    private void SubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMousePressed
        Submit.setForeground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMousePressed

    private void SubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseExited
        Submit.setForeground(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitMouseExited

    private void SubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseEntered
        Submit.setForeground(Color.blue);
    }//GEN-LAST:event_SubmitMouseEntered

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        JL52.setVisible(true);
        int a = JT1();
        int b = JP1();
        int c = JP2();
        int d = JT2();
        int e = JT3();
        if (a == 0) {
        } else if (b == 0) {
        } else if (c == 0) {
        } else if (d == 0) {
        } else if (e == 0) {
        } else {
            try {
                con = Connective.getConnection();
                String sql = "insert into User_details values (null,?,?,?,?)";
                pst = con.prepareStatement(sql);
                pst.setString(1, JT1.getText());
                pst.setString(2, JP1.getText());
                pst.setString(3, JT2.getText());
                pst.setString(4, JT3.getText());
                int executeUpdate = pst.executeUpdate();
                if (executeUpdate != 0) {
                    String sq = "call createtable (' + JT1.getText() + ');";
                    pst = con.prepareStatement(sq);
                    int executeUpdate1 = pst.executeUpdate();
                    pst.close();
                    con.close();
                    int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Congratulation ! You have registered successfully.Do you want login now?", "", JOptionPane.YES_NO_OPTION);
                    if (showConfirmDialog == JOptionPane.YES_OPTION) {
                        Open.LI(JT1.getText());
                        dispose();
                    }
                }

            } catch (HeadlessException ex) {
                System.out.println(ex);
            } catch (SQLException ex) {
                System.out.println(ex);
            } catch (ClassNotFoundException ex) {
                System.out.println(ex);

            }
        }
    }//GEN-LAST:event_SubmitMouseClicked

    private void JP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP2MouseExited
        JL31.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_JP2MouseExited

    private void JP2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP2MouseEntered
        JL31.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_JP2MouseEntered

    private void JP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP2MouseClicked
        JL32.setVisible(false);
        JP1();
    }//GEN-LAST:event_JP2MouseClicked

    private void JP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP1MouseExited
        JL21.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_JP1MouseExited

    private void JP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP1MouseEntered
        JL21.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_JP1MouseEntered

    private void JP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP1MouseClicked
        JL22.setVisible(false);
        JT1();
        JP2.setText("");
    }//GEN-LAST:event_JP1MouseClicked

    private void JT3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT3MouseClicked
        JL32.setVisible(true);
        JL42.setVisible(false);
        JT2();
    }//GEN-LAST:event_JT3MouseClicked

    private void JT1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT1MouseExited
        JL11.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_JT1MouseExited

    private void JT1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT1MouseEntered
        JL11.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_JT1MouseEntered

    private void JT1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT1MouseClicked
        JT2.setEnabled(false);
        JP1.setEnabled(false);
        JP2.setEnabled(false);
        JT3.setEnabled(false);
        JL12.setVisible(false);
    }//GEN-LAST:event_JT1MouseClicked

    private void JT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT2ActionPerformed

    private void JT2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT2MouseClicked
        JL42.setVisible(false);
        JP2();
    }//GEN-LAST:event_JT2MouseClicked

    private void Cancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MouseClicked
        Open.LI();
        dispose();
    }//GEN-LAST:event_Cancel1MouseClicked

    private void Cancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MouseEntered
        Cancel1.setForeground(Color.blue);
    }//GEN-LAST:event_Cancel1MouseEntered

    private void Cancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MouseExited
        Cancel1.setForeground(null);       // TODO add your handling code here:
    }//GEN-LAST:event_Cancel1MouseExited

    private void Cancel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MousePressed
        Cancel1.setForeground(Color.red);
    }//GEN-LAST:event_Cancel1MousePressed

    private void Cancel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel1MouseReleased
        Cancel1.setForeground(null); // TODO add your handling code here:
    }//GEN-LAST:event_Cancel1MouseReleased

    private void JT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT1ActionPerformed



    private int JT1() {
        JL12.setVisible(true);
        try {
            con = Connective.getConnection();
            String sql = "select * from User_Details where User_name=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, JT1.getText());
            rs = pst.executeQuery();
            if (JT1.getText().length() == 0) {
                JL12.setText("Can't empty");
                JL12.setForeground(new java.awt.Color(255, 0, 0));
            } else if (JT1.getText().length() > 8) {
                JL12.setText("Too long");
                JL12.setForeground(new java.awt.Color(255, 0, 0));
            } else if (!use.matcher(JT1.getText()).find()) {
                JL12.setText("Incorrect type");
                JL12.setForeground(new java.awt.Color(255, 0, 0));
            } else if (rs.next()) {
                JL12.setText("Has been used");
                JL12.setForeground(new java.awt.Color(255, 0, 0));
            } else {
                JL12.setText("  √");
                JL12.setForeground(new java.awt.Color(0, 200, 0));
                JP1.setEnabled(true);
                JT1.setEnabled(false);
                JT2.setEnabled(false);
                JP2.setEnabled(false);
                JT3.setEnabled(false);
                rs.close();
                pst.close();
                con.close();
                return 1;
            }
            rs.close();
            pst.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (SQLException ex) {
            System.out.println(ex);
        }

        return 0;
    }

    private int JT2() {
        JL42.setVisible(true);
        Connective connective = new Connective();
        try {
            con = connective.getConnection();
            String sql = "select * from User_Details where User_phone=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, JT2.getText());
            rs = pst.executeQuery();
            if (JP1.getText().length() == 0) {
                JL42.setText("Can't empty");
                JL42.setForeground(new java.awt.Color(255, 0, 0));
            } else if (!phone.matcher(JT2.getText()).find()) {
                JL42.setText("Incorrect type");
                JL42.setForeground(new java.awt.Color(255, 0, 0));
            } else if (rs.next()) {
                JL42.setText("Has been used");
                JL42.setForeground(new java.awt.Color(255, 0, 0));
            } else {
                JT3.setEnabled(true);
                JT2.setEnabled(false);
                JP2.setEnabled(false);
                JP1.setEnabled(false);
                JT1.setEnabled(false);
                JL42.setForeground(new java.awt.Color(0, 200, 0));
                JL42.setText("  √");
                rs.close();
                pst.close();
                con.close();
                return 1;
            }
            rs.close();
            pst.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        return 0;
    }

    private int JT3() {
        JL52.setVisible(true);
        Connective connective = new Connective();
        try {
            con = Connective.getConnection();
            String sql = "select * from User_Details where User_email=?";
            pst = con.prepareStatement(sql);
            pst.setString(1, JT3.getText());
            rs = pst.executeQuery();
            if (JT3.getText().length() == 0) {
                JL52.setForeground(new java.awt.Color(255, 0, 0));
                JL52.setText("Can't empty");
            } else if (!email.matcher(JT3.getText()).find()) {
                JL52.setForeground(new java.awt.Color(255, 0, 0));
                JL52.setText("Incorrect type");
            } else if (rs.next()) {
                JL52.setForeground(new java.awt.Color(255, 0, 0));
                JL52.setText("Has been used");
            } else {
                JL52.setText("  √");
                JL52.setForeground(new java.awt.Color(0, 200, 0));
                rs.close();
                pst.close();
                con.close();
                return 1;

            }
            rs.close();
            pst.close();
            con.close();
        } catch (ClassNotFoundException ex) {
            System.out.println(ex
            );
        } catch (SQLException ex) {
            System.out.println(ex
            );
        }
        return 0;
    }

    private int JP1() {
        JL22.setVisible(true);
        if (JP1.getText().length() == 0) {
            JL22.setText("Can't empty");
            JL22.setForeground(new java.awt.Color(255, 0, 0));
        } else if (JP1.getText().length() < 8) {
            JL22.setForeground(new java.awt.Color(255, 0, 0));
            JL22.setText("Too short");
        } else if (!passw.matcher(JP1.getText()).find()) {
            JL22.setText("Incorrect type");
            JL22.setForeground(new java.awt.Color(255, 0, 0));
        } else {
            JL22.setForeground(new java.awt.Color(0, 200, 0));
            JP2.setEnabled(true);
            JP1.setEnabled(false);
            JT2.setEnabled(false);
            JT1.setEnabled(false);
            JT3.setEnabled(false);
            JL22.setText("  √");
            return 1;

        }
        return 0;
    }

    private int JP2() {
        JL32.setVisible(true);
        if (JP1.getText().length() == 0) {
            JL32.setText("Can't empty");
            JL32.setForeground(new java.awt.Color(255, 0, 0));
        } else if (!JP1.getText().equals(JP2.getText())) {
            JL32.setText("Not same");
            JL32.setForeground(new java.awt.Color(255, 0, 0));
        } else {
            JT2.setEnabled(true);
            JP2.setEnabled(false);
            JP1.setEnabled(false);
            JT1.setEnabled(false);
            JT3.setEnabled(false);
            JL32.setForeground(new java.awt.Color(0, 200, 0));
            JL32.setText("  √");
            return 1;
        }
        return 0;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Cancel1;
    private javax.swing.JLabel JL11;
    private javax.swing.JLabel JL12;
    private javax.swing.JLabel JL21;
    private javax.swing.JLabel JL22;
    private javax.swing.JLabel JL31;
    private javax.swing.JLabel JL32;
    private javax.swing.JLabel JL42;
    private javax.swing.JLabel JL52;
    private javax.swing.JPasswordField JP1;
    private javax.swing.JPasswordField JP2;
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
